export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const OPEN_TYPE_SELECTION_MODAL = 'OPEN_TYPE_SELECTION_MODAL';
export const CLOSE_TYPE_SELECTION_MODAL = 'CLOSE_TYPE_SELECTION_MODAL';

export const QUIZ_DATA_ON_SUBMIT_SUCCESS = 'QUIZ_DATA_ON_SUBMIT_SUCCESS';
export const QUIZ_DATA_ON_SUBMIT_FAIL = 'QUIZ_DATA_ON_SUBMIT_FAIL';
